<?php
//error_reporting(E_ALL); ini_set('display_errors', '1');
ini_set('max_execution_time', 300);
require __DIR__ . "/cron_includes.php";

$sql = "SELECT DISTINCT item FROM auctions";
$result = mysqli_query($conn, $sql);


$sql2 = "SELECT * FROM items";
$result2 = mysqli_query($conn, $sql2);
$alreadydid = array();

// $last_sql = "SELECT MAX(last) AS last FROM item_status";
// $last_result = mysqli_query($conn, $last_sql);
// $last = mysqli_fetch_assoc($last_result)['last'];
// echo "Last: ".$last. PHP_EOL;

// while($row = mysqli_fetch_assoc($result2)){
//     array_push($alreadydid, $row['item']);
// }


$sql = 'INSERT INTO items (item, name) VALUES ';
$i = 0;

$oauthToken = getAccessToken($clientId, $clientSecret);

while($row = mysqli_fetch_assoc($result)){
    if(!in_array($row['item'], $alreadydid)){
        $response = getItemInfo($row['item'], $realmRegion, $oauthToken);
        var_dump($response);
        echo "Before ".$row['item'] ."  auc  ". $i. PHP_EOL;

        if($response != false){
            echo "After  ".$row['item'] ."  auc  ". $i. PHP_EOL;
            $response = getItemInfo($row['item'], $realmRegion, $oauthToken);

            
            $responseObject = json_decode($response, true)['name'];
            
            $name = str_replace('"','""',$responseObject);
            $sql = $sql . ' ('.$row['item'].', "'.$name.'"),';
            ++$i;
            if($i == 45) {
                $sql = substr($sql, 0, -1);
                $sql = $sql .";";
                mysqli_query($conn, $sql);
                exit();

            }
        }
    }
}







if($i > 0){
    $sql = substr($sql, 0, -1);
    $sql = $sql .";";
    mysqli_query($conn, $sql);
}


function getAccessToken($clientId, $clientSecret) {
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    //Getting the OAuth token
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, "https://us.battle.net/oauth/token");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_USERPWD, $clientId.':'.$clientSecret);

    $headers = array();
    $headers[] = "Content-Type: application/x-www-form-urlencoded";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $oauthToken = json_decode(curl_exec($ch), true)["access_token"];
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);

    return $oauthToken;
}

function getItemInfo($item, $realmRegion, $oauthToken) {
    //Getting the AH data json link form the api
    $ch = curl_init();
    
    curl_setopt($ch, CURLOPT_URL, 'https://'. $realmRegion .'.api.blizzard.com/wow/item/'. $item .'?locale=en_GB&access_token=' . $oauthToken);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
    
    
    $headers = array();
    $headers[] = "Accept: application/json";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
    $response = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);

    return $response;
}


?>
